# Generated by Django 3.1 on 2020-09-01 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item',
            new_name='listing',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
