# Generated by Django 3.1 on 2020-09-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200901_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
